default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: rails
  password: password

development:
  <<: *default
  database: nityamworld_development

test:
  <<: *default
  database: nityamworld_test

production:
  <<: *default
  database: nityamworld_production